import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated coverage report + ephemeral agent git worktrees (both
    // git-ignored). Linting them surfaces stale/generated code that isn't ours.
    "coverage/**",
    ".claude/**",
    // Build output for the Electron shell — BOTH of them, and both are
    // git-ignored, same class as the two entries above. eslint does NOT read
    // .gitignore, so being git-ignored buys nothing here.
    //   dist/    = tsc output, CommonJS by design.
    //   release/ = the packaged app, which embeds the ENTIRE Next standalone
    //              server (~90 MB of generated JS).
    // Either one reports a wall of `no-require-imports` errors about code
    // nobody wrote, and the whole-repo lint runs at --max-warnings=0, so that
    // is a hard fail on generated bytes. Measured: with only dist/** ignored,
    // `npx eslint --max-warnings=0` still exited 1 on release/**, and took
    // minutes because it was parsing the packaged server.
    "desktop/dist/**",
    "desktop/release/**",
  ]),
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@heroicons/react",
              message:
                "Icons come from src/app/icons.ts. @heroicons/react was removed app-wide (tech-debt TD-8).",
            },
          ],
          patterns: [
            {
              group: ["@heroicons/react/*"],
              message:
                "Icons come from src/app/icons.ts. @heroicons/react was removed app-wide (tech-debt TD-8).",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
