// Application version metadata: version, build date, milestone codename,
// repo/license links, and the Version-popover highlight keys.
// Per-version history lives in CHANGELOG.md (repo root) — the authoritative
// changelog. APP_BUILD_DATE is the date of the last build.
export const APP_VERSION = "0.244.0";
export const APP_BUILD_DATE = "2026-08-17"; // 0.244.0: every activity entry records who made the change — you, the assistant, or an integration — and the assistant is told what changed recently (Waldrop)
/** Minor-series milestone codename (sci-fi/fantasy author names). The
 *  0.244.x line is "Waldrop" (Howard Waldrop, SF/fantasy short-fiction author).
 *  0.243.x was "Aaronovitch" (Ben Aaronovitch, urban-fantasy author).
 *  0.242.x was "Ashby" (Madeline Ashby, SF author).
 *  0.241.x was "Tuttle" (Lisa Tuttle, SF/fantasy author).
 *  0.240.x was "Elliott" (Kate Elliott, prolific SF/fantasy author).
 *  0.239.x was "Rusch" (Kristine Kathryn Rusch, prolific SF/fantasy author).
 *  0.238.x was "Attanasio" (A.A. Attanasio, SF/fantasy author).
 *  0.237.x was "Roberson" (Chris Roberson, SF/fantasy author).
 *  0.236.x was "Sheldon" (the rich-text toolbar's keyboard contract slice —
 *  no bio recorded for it here; not asserting one now rather than guessing).
 *  0.235.x was "Lackey" (Mercedes Lackey, prolific fantasy author).
 *  0.234.x was "Anders" (Charlie Jane Anders, contemporary SF/fantasy author).
 *  0.233.x was "Reed" (Robert Reed, prolific SF short-fiction author).
 *  ★★ 0.224.0 IS A PERMANENTLY DEAD NUMBER — do not reuse it. The 0.226.0 line
 *  was built and numbered 0.224.0 while unpushed; main could not wait for it,
 *  deliberately skipped 0.224.0 and shipped 0.225.0 "Walton" first, so keeping
 *  0.224.0 would have meant a release commit naming a version no build ever
 *  reported. The gap is the record of why.
 *  ★ Fetch before bumping. 0.221.0 "Kavan" shipped on main while the 0.222.0
 *  branch was in review and forced a renumber at merge time — and it happened
 *  AGAIN here: this branch's own bump (0.237.0 "Attanasio") collided with
 *  0.236.0 "Sheldon" AND 0.237.0 "Roberson" both landing on main first while
 *  it sat unpushed, forcing a renumber to 0.238.0 at merge time. A codename
 *  is unique per minor line and no gate here checks either the number or the
 *  name — the only defence is looking at CHANGELOG.md first. ★★ Match the NAME,
 *  not the dash: older CHANGELOG entries use an em-dash and newer ones a hyphen,
 *  so a dash-anchored grep reports used names as free. */
export const APP_MILESTONE = "Waldrop";
/** Version with its milestone codename for UI display, e.g. `0.39.0 "Tchaikovsky"`. */
export const APP_VERSION_LABEL = `${APP_VERSION} "${APP_MILESTONE}"`;
export const APP_REPO_URL = "https://www.example.com";

/** Open-source license (SPDX id) and its canonical reference URL, shown in the
 *  Settings footer and the Help panel. Mirrors package.json `license`. */
export const APP_LICENSE = "EUPL-1.2";
export const APP_LICENSE_URL =
  "https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12";

/** Translation keys for the high-level feature highlights shown in the
 *  Version popover. Update both EN and DE in i18n.ts when you add to this. */
export const APP_HIGHLIGHT_KEYS = [
  "versionHighlightChat",
  "versionHighlightVoice",
  "versionHighlightStorage",
  "versionHighlightJira",
  "versionHighlightReports",
  "versionHighlightGantt",
  "versionHighlightRaid",
  "versionHighlightResources",
  "versionHighlightActivity",
  "versionHighlightContacts",
  "versionHighlightExport",
  "versionHighlightNotifications",
  "versionHighlightWorkspace",
  "versionHighlightSecurity",
  "versionHighlightPerformance",
  "versionHighlightBudget",
  "versionHighlightPolish",
  "versionHighlightBudgetEdit",
  "versionHighlightTheme",
  "versionHighlightPalette",
  "versionHighlightTableResize",
  "versionHighlightRaidReport",
  "versionHighlightReportsSortFilter",
  "versionHighlightPrintReports",
  "versionHighlightM365Auth",
  "versionHighlightSharepointStorage",
  "versionHighlightOutlookContacts",
  "versionHighlightOutlookCalendar",
  "versionHighlightTursoStorage",
  "versionHighlightTursoRelational",
  "versionHighlightStorageConvert",
  "versionHighlightStorageUnreachable",
  "versionHighlightModernLayout",
  "versionHighlightFullPageEdit",
  "versionHighlightTableRestyle",
  "versionHighlightSidebarPolish",
  "versionHighlightPaneResize",
  "versionHighlightConsistency",
  "versionHighlightBudgetModes",
  "versionHighlightBudgetReport",
  "versionHighlightComposableReports",
  "versionHighlightDashboard",
  "versionHighlightMilestones",
  "versionHighlightEarnedValue",
  "versionHighlightEvmRag",
  "versionHighlightBudgetRag",
  "versionHighlightUiRefinements",
  "versionHighlightTrends",
  "versionHighlightChangeLog",
  "versionHighlightRaidReview",
  "versionHighlightStakeholders",
  "versionHighlightStakeholderReport",
  "versionHighlightModes",
  "versionHighlightClarke",
  "versionHighlightFieldFeedback",
  "versionHighlightButler",
  "versionHighlightVinge",
  "versionHighlightTursoMultiProject",
  "versionHighlightSpDocLinks",
  "versionHighlightFieldVisibility",
  "versionHighlightTemplates",
  "versionHighlightPerProjectFunctions",
  "versionHighlightTemplateSuggest",
  "versionHighlightRecovery",
  "versionHighlightUiPolishBatch",
  "versionHighlightActionCenter",
  "versionHighlightSnoozeActions",
  "versionHighlightActionChips",
  "versionHighlightScheduleWorkload",
  "versionHighlightUiBatch",
  "versionHighlightDocuments",
  "versionHighlightLoadFormats",
  "versionHighlightConfidenceRanking",
  "versionHighlightCreateTask",
  "versionHighlightUiBatch85",
  "versionHighlightAssignOwner",
  "versionHighlightDraftMessage",
  "versionHighlightCommTemplates",
  "versionHighlightCommTemplatesRich",
  "versionHighlightCommTemplatesVersions",
  "versionHighlightCommTemplatesSend",
  "versionHighlightEscalate",
  "versionHighlightRebaseline",
  "versionHighlightDesktopNotify",
  "versionHighlightLearning",
  "versionHighlightCalendarPush",
  "versionHighlightUiBatchVm",
  "versionHighlightAiContextCore",
  "versionHighlightAiAskClaude",
  "versionHighlightUiBatch0990",
  "versionHighlightUiBatch0100",
  "versionHighlightUiBatch0101",
  "versionHighlightAiWriteTools",
  "versionHighlightAiDocIngest",
  "versionHighlightAiCreateWizard",
  "versionHighlightAiActionSuggestions",
  "versionHighlightScheduledJobs",
  "versionHighlightInstallable",
  "versionHighlightTaskStatus",
  "versionHighlightKanban",
  "versionHighlightWeightSuggest",
  "versionHighlightProjectImport",
  "versionHighlightSteering",
  "versionHighlightTour",
  "versionHighlightTimezones",
  "versionHighlightTimezoneDisplay",
  "versionHighlightTimezoneCalendar",
  "versionHighlightAiFeatureGuide",
  "versionHighlightJiraEncryption",
  "versionHighlightLandingCockpit",
  "versionHighlightMilestoneHorizon",
  "versionHighlightCoaching",
  "versionHighlightTrendArrows",
  "versionHighlightBurndownSparkline",
  "versionHighlightDashboardDensity",
  "versionHighlightClickThrough",
  "versionHighlightDeepLinkFlash",
  "versionHighlightGlobalSearch",
  "versionHighlightSavedViews",
  "versionHighlightSavedViewsPanels",
  "versionHighlightSavedViewsReports",
  "versionHighlightUiBatch0134",
  "versionHighlightInteractionStates",
  "versionHighlightBulkEdit",
  "versionHighlightDensityRhythm",
  "versionHighlightResponsiveGrids",
  "versionHighlightTimelog",
  "versionHighlightDualCi",
  "versionHighlightMockupPolish",
  "versionHighlightSetupWizard",
  "versionHighlightPortfolioHealth",
  "versionHighlightTimelogWorkflow",
  "versionHighlightAiMasterSwitch",
  "versionHighlightMasonry",
  "versionHighlightModelPicker",
  "versionHighlightActionGrouping",
  "versionHighlightActionLayout",
  "versionHighlightActionProviders",
  "versionHighlightActionInlineCtas",
  "versionHighlightMultiUpload",
  "versionHighlightHelpLayout",
  "versionHighlightChatFullWidth",
  "versionHighlightViewTips",
  "versionHighlightAnalyzeModal",
  "versionHighlightHelpRedesign",
  "versionHighlightFloatingHelpTabs",
  "versionHighlightDocumentsCards",
  "versionHighlightColumnVisibility",
  "versionHighlightViewChrome",
  "versionHighlightPrintMultipage",
  "versionHighlightColorSchemes",
  "versionHighlightResizeAnchor",
  "versionHighlightNextActionsRedesign",
  "versionHighlightJiraMultiProject",
  "versionHighlightStakeholderDrag",
  "versionHighlightCalendarWriteback",
  "versionHighlightCalendarChange",
  "versionHighlightCalendarAbsence",
  "versionHighlightCalendarPull",
  "versionHighlightCalendarPullTask",
  "versionHighlightCalendarPullRaidChange",
  "versionHighlightCalendarPullAbsence",
  "versionHighlightCalendarAutoPull",
  "versionHighlightInlineAiEdit",
  "versionHighlightInlineAiEditSp2",
  "versionHighlightSearchCoverage",
  "versionHighlightActivityDiff",
  "versionHighlightKeyboardA11y",
  "versionHighlightWorkloadActionable",
  "versionHighlightResourceEnhance",
  "versionHighlightResourceFollowup",
  "versionHighlightTimelogCustomer",
  "versionHighlightGanttBaseline",
  "versionHighlightStatusDigest",
  "versionHighlightUndo",
  "versionHighlightUxBatchAldiss",
  "versionHighlightRedo",
  "versionHighlightIdIntegrity",
  "versionHighlightLiveNames",
  "versionHighlightSteeringReports",
  "versionHighlightColorSchemesDark",
  "versionHighlightSchemeDehardcode",
  "versionHighlightSchemeDatabase",
  "versionHighlightModalResize",
  "versionHighlightFeatureGuidance",
  "versionHighlightUiBatch0187",
  "versionHighlightFieldUndo",
  "versionHighlightOfficeIngest",
  "versionHighlightM365SignInFix",
  "versionHighlightDeepLinkEditor",
  "versionHighlightResourceClearFix",
  "versionHighlightPopoverClip",
  "versionHighlightProcessAttachment",
  "versionHighlightFloatingEditor",
  "versionHighlightOpenPointsActions",
  "versionHighlightRaidInquiry",
  "versionHighlightTaskNoteLog",
  "versionHighlightGanttMilestonePlacement",
  "versionHighlightUndoLabels",
  "versionHighlightToastPause",
  "versionHighlightAiErrorDetail",
  "versionHighlightPullContacts",
  "versionHighlightKnowledgeLinks",
  "versionHighlightTaskDedup",
  "versionHighlightAppRename",
  "versionHighlightThemeDecouple",
  "versionHighlightUiTokenRename",
  "versionHighlightHeroicons",
  "versionHighlightKnowledgeItems",
  "versionHighlightAiSettingsTool",
  "versionHighlightProjectOverrides",
  "versionHighlightProjectViewMode",
  "versionHighlightInsights",
  "versionHighlightInsightsRecommend",
  "versionHighlightInsightsOutcome",
  "versionHighlightInsightsDigest",
  "versionHighlightCostReason",
  "versionHighlightBurndownFollowPlan",
  "versionHighlightChatFormatting",
  "versionHighlightDirectoryHideExternal",
  "versionHighlightRichNotes",
  "versionHighlightTaskDescription",
  "versionHighlightBudgetCpi",
  "versionHighlightTimelogScopeMemory",
  "versionHighlightPolishR1",
  "versionHighlightKanbanSwimlanes",
  "versionHighlightDashboardR3",
  "versionHighlight0201",
  "versionHighlight0202",
  "versionHighlight02023",
  "versionHighlight0203",
  "versionHighlight0207",
  "versionHighlight0208",
  "versionHighlight0209",
  "versionHighlight0210",
  "versionHighlight0211",
  "versionHighlight0212",
  "versionHighlight0213",
  "versionHighlight0214",
  "versionHighlight0215",
  "versionHighlight0216",
  "versionHighlight0217",
  "versionHighlight0218",
  "versionHighlight0219",
  "versionHighlight0220",
  "versionHighlight0222",
  "versionHighlight0223",
  "versionHighlight0225",
  "versionHighlight0226",
  "versionHighlight0227",
  "versionHighlight0228",
  "versionHighlight0229",
  "versionHighlight0230",
  "versionHighlight0231",
  "versionHighlight0232",
  "versionHighlight0233",
  "versionHighlight0234",
  "versionHighlight0235",
  "versionHighlight0237",
  "versionHighlightTaskListAlign",
  "versionHighlightActivityWorkspace",
  "versionHighlightDashboardArrange",
  "versionHighlightHistorySearch",
  "versionHighlightCsvQuoting",
  "versionHighlightRichExport",
  "versionHighlightActorAttribution",
] as const;
